### ISSUE TITLE
Pysnmp will no work with pyasn1 0.5.0 (last release before works fine)

### ISSUE THREAD

**Issue by bauergeorg** [pyasn1/pyasn1#34] opened 2023-04-27 13:41 UTC
Pysnmp (4.4.12, no change since 2019) will no work with pyasn1 0.5.0. The last release before works fine!

```
(hil) rohbot@rohbot001:~/ee-python-hil $ /home/rohbot/venvs/hil/bin/python3 /home/rohbot/ee-python-hil/test.py
Traceback (most recent call last):
  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
  File "/usr/lib/python3.7/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.7/asyncore.py", line 188, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python3.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/lib/python3.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python3.7/asyncore.py", line 422, in handle_read_event
    self.handle_read()
  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 170, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/carrier/base.py", line 85, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/proto/rfc3412.py", line 291, in receiveMessage
    msgVersion = verdec.decodeMessageVersion(wholeMsg)
  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/proto/api/verdec.py", line 17, in decodeMessageVersion
    recursiveFlag=False, substrateFun=lambda a, b, c: (a, b[:c])
  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 2003, in __call__
    for asn1Object in streamingDecoder:
  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 1919, in __iter__
    self._substrate, self._asn1Spec, **self._options):
  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 1781, in __call__
    self, substrateFun, **options):
  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 654, in valueDecoder
    for chunk in substrateFun(asn1Object, substrate, length, options):
TypeError: <lambda>() takes 3 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohbot/ee-python-hil/test.py", line 5, in <module>
    mac = ps.getMacAddress()
  File "/home/rohbot/ee-python-hil/TestingSystem/Interface/Brennenstuhl/IF_PowerStripWebLine.py", line 121, in getMacAddress
    ans = quicksnmp.get(self.hostAddress, [oid], hlapi.CommunityData('public'))
  File "/home/rohbot/ee-python-hil/TestingSystem/Interface/Brennenstuhl/quicksnmp.py", line 27, in get
    return fetch(handler, 1)[0]
  File "/home/rohbot/ee-python-hil/TestingSystem/Interface/Brennenstuhl/quicksnmp.py", line 84, in fetch
    bla = next(handler)
  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 113, in getCmd
    snmpEngine.transportDispatcher.runDispatcher()
  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 50, in runDispatcher
    raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))
pysnmp.error.PySnmpError: poll error: Traceback (most recent call last):
;  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "/usr/lib/python3.7/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
;  File "/usr/lib/python3.7/asyncore.py", line 188, in poll2
    readwrite(obj, flags)
;  File "/usr/lib/python3.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
;  File "/usr/lib/python3.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
;  File "/usr/lib/python3.7/asyncore.py", line 422, in handle_read_event
    self.handle_read()
;  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 170, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
;  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/carrier/base.py", line 85, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
;  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
;  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/proto/rfc3412.py", line 291, in receiveMessage
    msgVersion = verdec.decodeMessageVersion(wholeMsg)
;  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pysnmp/proto/api/verdec.py", line 17, in decodeMessageVersion
    recursiveFlag=False, substrateFun=lambda a, b, c: (a, b[:c])
;  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 2003, in __call__
    for asn1Object in streamingDecoder:
;  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 1919, in __iter__
    self._substrate, self._asn1Spec, **self._options):
;  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 1781, in __call__
    self, substrateFun, **options):
;  File "/home/rohbot/venvs/hil/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 654, in valueDecoder
    for chunk in substrateFun(asn1Object, substrate, length, options):
;TypeError: <lambda>() takes 3 positional arguments but 4 were given
caused by <class 'TypeError'>: <lambda>() takes 3 positional arguments but 4 were given
```

**Comment by lextm** [comment] 2023-04-27 14:10
duplicate of #28

**Closed** 2023-04-27 17:26 UTC
