### ISSUE TITLE
Removing compats.octet breaks pysnmp and should be denoted with proper SEMVER

### ISSUE THREAD

**Issue by jmcenteeIV** [pyasn1/pyasn1#79] opened 2024-09-24 00:04 UTC
This [change breaks](https://github.com/pyasn1/pyasn1/pull/60/files#diff-85ac7d71ce8ba54dde517d1deedf08313ad5c6a81e83a3bb4f22988fc641a8da) pysnmp.  I will be filing an issue in their repo as well (as mostly this is an issue of dependency management) but I think that the versioning should have reved to a major release based on the [semver spec](https://semver.org/).

Example error in question when updating to 0.6.1 from 0.6.0:
```
from pysnmp.hlapi import ObjectIdentity, ObjectType, UdpTransportTarget, UsmUserData
ModuleNotFoundError: No module named 'pyasn1.compat.octets'
```

**Comment by droideck** [comment] 2024-09-24 00:12
Closing as duplicate of https://github.com/pyasn1/pyasn1/issues/76

**Closed by droideck** 2024-09-24 00:12 UTC
