### ISSUE TITLE
No module named pyasn1.compat.octets found.

### ISSUE THREAD

**Issue by bseth15** [pyasn1/pyasn1#77] opened 2024-09-12 14:43 UTC
We started to get this exception after updating from 0.6.0 to 0.6.1

[2024-09-12T14:35:37.132Z]     from lib.snmp.snmp import snmp_v3_get_oid
[2024-09-12T14:35:37.132Z] lib/snmp/snmp.py:42: in <module>
[2024-09-12T14:35:37.132Z]     from pysnmp import hlapi
[2024-09-12T14:35:37.132Z] /home/user/.local/lib/python3.9/site-packages/pysnmp/hlapi/__init__.py:7: in <module>
[2024-09-12T14:35:37.132Z]     from pysnmp.proto.rfc1902 import *
[2024-09-12T14:35:37.132Z] /home/user/.local/lib/python3.9/site-packages/pysnmp/proto/rfc1902.py:9: in <module>
[2024-09-12T14:35:37.132Z]     from pysnmp.proto import rfc1155, error
[2024-09-12T14:35:37.132Z] /home/user/.local/lib/python3.9/site-packages/pysnmp/proto/rfc1155.py:10: in <module>
[2024-09-12T14:35:37.132Z]     from pysnmp.proto import error
[2024-09-12T14:35:37.132Z] /home/user/.local/lib/python3.9/site-packages/pysnmp/proto/error.py:9: in <module>
[2024-09-12T14:35:37.132Z]     from pysnmp import debug
[2024-09-12T14:35:37.132Z] /home/user/.local/lib/python3.9/site-packages/pysnmp/debug.py:8: in <module>
[2024-09-12T14:35:37.132Z]     from pyasn1.compat.octets import octs2ints
[2024-09-12T14:35:37.132Z] E   ModuleNotFoundError: No module named 'pyasn1.compat.octets'

**Comment by droideck** [comment] 2024-09-12 19:59
Closing as duplicate of #76

**Closed by droideck** 2024-09-12 19:59 UTC
