### ISSUE TITLE
DeprecationWarning: typeMap is deprecated. Please use TYPE_MAP instead.

### ISSUE THREAD

**Issue by Vuizur** [pyasn1/pyasn1#80] opened 2024-10-14 09:23 UTC
When using pyasn1 and testing using pytest, I get the warnings:
```
[Mon Oct 14 11:08:05.919973 2024] [wsgi:error] [pid 5920:tid 129333855258304]   haveNameConstant = hasattr(ast,'NameConstant')
[Mon Oct 14 11:08:06.961924 2024] [wsgi:error] [pid 5920:tid 129333855258304] /.venv/lib/python3.12/site-packages/pyasn1/codec/ber/encoder.py:952: DeprecationWarning: tagMap is deprecated. Please use TAG_MAP instead.
[Mon Oct 14 11:08:06.961936 2024] [wsgi:error] [pid 5920:tid 129333855258304]   warnings.warn(f"{attr} is deprecated. Please use {newAttr} instead.", DeprecationWarning)
[Mon Oct 14 11:08:06.961946 2024] [wsgi:error] [pid 5920:tid 129333855258304] /.venv/lib/python3.12/site-packages/pyasn1/codec/ber/encoder.py:952: DeprecationWarning: typeMap is deprecated. Please use TYPE_MAP instead.
[Mon Oct 14 11:08:06.961947 2024] [wsgi:error] [pid 5920:tid 129333855258304]   warnings.warn(f"{attr} is deprecated. Please use {newAttr} instead.", DeprecationWarning)
```

I am pretty sure that they come from the pyasn1 code itself (which apparently uses the deprecated syntax), because my code doesn't use these parameters (typeMap or TYPE_MAP). It would be nice to fix these warnings.

**Comment by droideck** [comment] 2024-10-15 20:04
To help diagnose the issue further, could you please provide a minimal code snippet that reproduces the warnings?

**Comment by idahogray** [comment] 2024-10-16 01:27
I also received this warning when I upgraded to Python 3.12 in my django project which uses the ldap3 package.

**Comment by Vuizur** [comment] 2024-10-17 07:04
I think I could also simply have met the ldap3 issue. 🤔

**Comment by droideck** [comment] 2024-10-17 14:45
Okay, sounds good!
I'll close it as 'Not a bug' for now.
Feel free to reopen it if you'll find a pyasn1 code reproducer! Thank you!

**Closed by droideck** 2024-10-17 14:45 UTC
